version: "3.9"

services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./backend/:/app/
    tty: true
  db:
    build:
      context: ./docker
      dockerfile: Postgres.Dockerfile
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    working_dir: /app
    volumes:
      - ./:/app/
    ports:
      - "5432:5432"