version: "3.9"

services:
  node:
    build:
      context: ./docker
      dockerfile: Node.Dockerfile
    working_dir: /app
    volumes:
      - ./frontend/:/app/
    command: bash -c "npm install && ng serve"
    ports:
      - "4200:4200"
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./api/:/app/
    command: bash -c "composer install && symfony server:start"
    ports:
      - "80:8000"
  db:
    build:
      context: ./docker
      dockerfile: Postgres.Dockerfile
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    working_dir: /app
    volumes:
      - ./:/app/
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

volumes:
  db-data: