version: "3.9"

services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./backend/:/app/
    command: symfony server:start
    ports:
      - "80:8000"
  db:
    build:
      context: ./docker
      dockerfile: Postgres.Dockerfile
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    working_dir: /app
    volumes:
      - ./:/app/
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

volumes:
  db-data: